[tool.poetry]
name = "modern-bert-mlx"
version = "0.1.0"
description = "ModernBERT Implemented for Apple Silicon"
authors = ["Aditesh Kumar <27091329+aramuk@users.noreply.github.com>"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
